global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['laradock-prometheus:9090']
  - job_name: 'redis-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
        - targets:
            - 'laradock-redis-exporter:9121'
  - job_name: 'activemq_artemis'
    scrape_interval: 5s
    static_configs:
      - targets: ['acqueue:9404']
